const menu = [
    {
        id: 1,
        title: 'Hamburger',
        category: 'burgers',
        price: 3.00,
        img:
            'https://imgur.com/tnrs1cI.jpg',
        desc: `Ingredients: patty, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 2,
        title: 'Cheeseburger',
        category: 'burgers',
        price: 3.20,
        img:
            'https://imgur.com/clfVpYS.jpg',
        desc: `Ingredients: patty, cheese, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 3,
        title: 'Baconburger',
        category: 'burgers',
        price: 3.50,
        img: 'https://imgur.com/2dQ6hCd.jpg',
        desc: `Ingredients: patty, bacon, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 4,
        title: 'Burgeria',
        category: 'burgers',
        price: 4.00,
        img:
            'https://imgur.com/O9KRrg8.jpg',
        desc: `Ingredients: 2 patty's, cheese, bacon, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 5,
        title: 'Chicken Burger',
        category: 'burgers',
        price: 3.00,
        img:
            'https://imgur.com/k67DGLK.jpg',
        desc: `Ingredients: steak, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 6,
        title: 'Crispy Chicken',
        category: 'burgers',
        price: 3.20,
        img:
            'https://imgur.com/ujVRYuQ.jpg',
        desc: `Ingredients: crispy steak, pickles, lettuce, tomato, onion, sauces`,
    },
    {
        id: 7,
        title: 'Ham Toast',
        category: 'toasts',
        price: 3.00,
        img:
            'https://leskovac.mk/wp-content/uploads/2020/12/tost-so-sunka-scaled.jpg',
        desc: `Ingredients: ham, cheese, sauces`,
    },
    {
        id: 8,
        title: 'Pepperoni Toast',
        category: 'toasts',
        price: 3.20,
        img: 'https://leskovac.mk/wp-content/uploads/2020/12/tost-kulen-scaled.jpg',
        desc: `Ingredients: pepperoni, cheese, sauces`,
    },
    {
        id: 9,
        title: 'Bacon Toast',
        category: 'toasts',
        price: 3.50,
        img: 'https://leskovac.mk/wp-content/uploads/2020/12/tost-so-slanina.jpg',
        desc: `Ingredients: bacon, cheese, sauces`,
    },
    {
        id: 10,
        title: 'Small Fries',
        category: 'sides',
        price: 1.50,
        img: 'https://imgur.com/eKlTttX.jpg',
        desc: ``,
    },
    {
        id: 11,
        title: 'Medium Fries',
        category: 'sides',
        price: 2.00,
        img: 'https://imgur.com/GzKtb8f.jpg',
        desc: ``,
    },
    {
        id: 12,
        title: 'Large Fries',
        category: 'sides',
        price: 2.50,
        img: 'https://imgur.com/3ZN631S.jpg',
        desc: ``,
    },
    {
        id: 13,
        title: 'Tomato sauce',
        category: 'sides',
        price: 0.50,
        img: 'https://imgur.com/yVoDaNA.jpg',
        desc: ``,
    },
    {
        id: 14,
        title: 'Curry sauce',
        category: 'sides',
        price: 0.80,
        img: 'https://imgur.com/VEW04uJ.jpg',
        desc: ``,
    },
    {
        id: 15,
        title: 'Hot sauce',
        category: 'sides',
        price: 0.50,
        img: 'https://imgur.com/svEd916.jpg',
        desc: ``,
    },
    {
        id: 16,
        title: 'Coca Cola',
        category: 'drinks',
        price: 1.30,
        img: 'https://imgur.com/RzFH4Gg.jpg',
        desc: ``,
    },
    {
        id: 17,
        title: 'Coca Cola Zero',
        category: 'drinks',
        price: 1.30,
        img: 'https://imgur.com/46Sec2L.jpg',
        desc: ``,
    },
    {
        id: 18,
        title: 'Fanta',
        category: 'drinks',
        price: 1.30,
        img: 'https://imgur.com/A7fC8Ba.jpg',
        desc: ``,
    },
    {
        id: 19,
        title: 'Schweppes',
        category: 'drinks',
        price: 1.30,
        img: 'https://imgur.com/u9U9tM6.jpg',
        desc: ``,
    },
    {
        id: 20,
        title: 'Water',
        category: 'drinks',
        price: 1.00,
        img: 'https://imgur.com/5iSEkxB.jpg',
        desc: ``,
    },
    {
        id: 21,
        title: 'Sparkling Water',
        category: 'drinks',
        price: 1.00,
        img: 'https://imgur.com/rRNGt6l.jpg',
        desc: ``,
    },

]
export default menu